# Generated by Django 4.1.2 on 2022-10-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post', models.TextField()),
                ('date', models.DateField(verbose_name='Date Posted')),
                ('time', models.TimeField(verbose_name='Time Posted')),
                ('recommend', models.BooleanField(default=False)),
            ],
        ),
    ]
