# Generated by Django 4.1.2 on 2022-11-05 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamereview',
            name='date',
        ),
        migrations.RemoveField(
            model_name='gamereview',
            name='time',
        ),
        migrations.AddField(
            model_name='gamereview',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
