# Generated by Django 4.1.2 on 2022-11-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_gamereview_date_remove_gamereview_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamereview',
            old_name='recommend',
            new_name='liked',
        ),
    ]
