# Generated by Django 4.1.2 on 2022-11-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_gamereview_lastupdated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamereview',
            old_name='liked',
            new_name='likedGame',
        ),
    ]
